language: julia

os:
        - osx
        - linux

julia:
        - 1.0
        - 1.3

env:
    global:
    - PYTHON=conda
    matrix:
    - MPMATH=true
    - MPMATH=false
notifications:
  email: false
before_install:
    #install mpmath to test functionallity
  - if [ $MPMATH = "true" ]; then julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.add("mpmath")';fi
